name: deploy-bwgr-tools

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Source Cleanup
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          rm -rf ${{ secrets.SOURCEDIR }}

    - name: Copy
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: ${{ secrets.SOURCEDIR }}

    - name: Build, Target Cleanup, Copy
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          cd ${{ secrets.SOURCEDIR }}
          nvm use 19.4.0
          npm i
          npm run build
          rm -rf ${{ secrets.TARGETDIR }}
          sudo cp -R ${{ secrets.SOURCEDIR }}/dist ${{ secrets.TARGETDIR }}